#name: Deploy Docusaurus Docs
#
#on:
#    push:
#        branches:
#            - main # oder master, je nachdem, was dein Hauptbranch ist
#
#permissions:
#    contents: read
#    pages: write
#    id-token: write
#
#jobs:
#    deploy:
#        runs-on: ubuntu-latest
#        steps:
#            - name: Checkout
#              uses: actions/checkout@v4
#
#            - name: Setup Node.js
#              uses: actions/setup-node@v4
#              with:
#                  node-version: '18'
#                  cache: 'npm'
#                  cache-dependency-path: 'documentation/package-lock.json' # Wichtig: Pfad zur Doku anpassen
#
#            - name: Install and Build Docusaurus
#              working-directory: ./documentation # Wichtig: Pfad zur Doku anpassen
#              run: |
#                  npm ci
#                  npm run build
#
#            - name: Setup Pages
#              uses: actions/configure-pages@v5
#
#            - name: Upload artifact
#              uses: actions/upload-pages-artifact@v3
#              with:
#                  path: ./documentation/build # Wichtig: Pfad zur Doku anpassen
#
#            - name: Deploy to GitHub Pages
#              id: deployment
#              uses: actions/deploy-pages@v4
