name: Run Tests

on:
   push:
      branches: [ "main" ]
   pull_request:
      branches: [ "main" ]

jobs:
   test:
      runs-on: ubuntu-latest
      strategy:
         fail-fast: false
         matrix:
            include:
               # Test Laravel 10
               -  laravel: '10.*'
                  php: '8.2'
                  testbench: '8.*'
                  phpunit: '10.*'

               # Test Laravel 11
               -  laravel: '11.*'
                  php: '8.2'
                  testbench: '9.*'
                  phpunit: '11.*'

               # Test Laravel 12
               -  laravel: '12.*'
                  php: '8.3'
                  testbench: '10.*'
                  phpunit: '12.*'

               # Test Laravel 12 on PHP 8.4
               -  laravel: '12.*'
                  php: '8.4'
                  testbench: '10.*'
                  phpunit: '12.*'

      name: P${{ matrix.php }} - L${{ matrix.laravel }}

      steps:
         -  name: Checkout code
            uses: actions/checkout@v4

         -  name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
               php-version: ${{ matrix.php }}
               extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
               coverage: none

         -  name: Install Composer dependencies
            run: |
               composer require "laravel/framework:${{ matrix.laravel }}" \
                 "orchestra/testbench:${{ matrix.testbench }}" \
                 "phpunit/phpunit:${{ matrix.phpunit }}" \
                 --no-interaction --no-update --dev
               composer update --prefer-stable --prefer-dist --no-interaction --no-progress --with-all-dependencies

         -  name: Execute tests
            run: vendor/bin/pest
