name: Run Tests

on:
   push:
      branches: [ "main" ]
   pull_request:
      branches: [ "main" ]

jobs:
   test:
      runs-on: ubuntu-latest
      strategy:
         fail-fast: false
         matrix:
            include:
               # Test Laravel 10
               -  laravel: '10.*'
                  php: '8.2'
                  testbench: '^8.0'
                  phpunit: '^10.0'
                  pest_version: '^2.0'

               # Test Laravel 11
               -  laravel: '11.*'
                  php: '8.2'
                  testbench: '^9.0'
                  phpunit: '^11.0'
                  pest_version: '^3.0'

               # Test Laravel 12 on PHP 8.3
               -  laravel: '12.*'
                  php: '8.3'
                  testbench: '^10.0'
                  phpunit: '^11.0' # CORRECTED from ^12.0
                  pest_version: '^3.0'

               # Test Laravel 12 on PHP 8.4
               -  laravel: '12.*'
                  php: '8.4'
                  testbench: '^10.0'
                  phpunit: '^11.0' # CORRECTED from ^12.0
                  pest_version: '^3.0'

      name: P${{ matrix.php }} - L${{ matrix.laravel }}

      steps:
         -  name: Checkout code
            uses: actions/checkout@v4

         -  name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
               php-version: ${{ matrix.php }}
               extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
               coverage: none

         -  name: Install Composer dependencies
            run: |
               # Step 1: Remove the lock file to force a fresh dependency resolution.
               rm -f composer.lock

               # Step 2: Replace conflicting constraints in composer.json for this specific job.
               composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
               composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
               composer require "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
               composer require "pestphp/pest:${{ matrix.pest_version }}" --dev --no-interaction --no-update
               composer require "pestphp/pest-plugin-laravel:${{ matrix.pest_version }}" --dev --no-interaction --no-update

               # Step 3: Run "update" to resolve and install the fresh set of dependencies.
               composer update --prefer-dist --no-interaction --no-progress

         -  name: Execute tests
            run: composer test
